pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                //sh 'mvn -B -DskipTests clean package'
                echo 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                //sh 'mvn test'
                echo 'mvn test'
            }
            post {
                always {
                    //junit 'target/surefire-reports/*.xml'
                    echo 'junit target/surefire-reports/*.xml'
                    
                }
            }
        }
        stage('Deliver') {
            steps {
                //sh './jenkins/scripts/deliver.sh'
                echo './jenkins/scripts/deliver.sh'
            }
        }
    }
}
